---

- hosts: all
  remote_user: root
  vars_files:
    - vars.yml

  roles:
    - docker
    - deploy

  pre_tasks:
    - name: upgrade all packages
      yum: name=* state=latest
    - name: install tools
      yum: name=htop,tmux,curl state=installed

  environment: env