---

- hosts: all
  remote_user: root
  vars:
    docker_compose_version: 1.6.0
    docker_volumes_version: 1.2

  vars_files:
    - vars.yml

  roles:
    - docker

  pre_tasks:
    - name: upgrade all packages
      yum: name=* state=latest
      with_items:
        - htop
        - tmux
        - curl
