# - include: docker.yml
# - include: docker-compose.yml

- import_role:
    name: geerlingguy.docker
- name: Copy docker-container.logrotate
  copy: src=docker-container.logrotate dest=/etc/logrotate.d/docker-container
